/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Cliente;
import Modelo.PaqueteTuristico;
import Modelo.Venta;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @authors [NombreAutores_Y_Codigo]
 * @version 1.0 - 20260518
 */
public class UsaGUIVenta extends javax.swing.JFrame {

    private static ArrayList<Venta> datosVentas = new ArrayList<>();
    private static ArrayList<Cliente> datosClientes = new ArrayList<>();

    /**
     * Creates new form UsaGUIVenta
     */
    public UsaGUIVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsaGUIVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsaGUIVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsaGUIVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsaGUIVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsaGUIVenta().setVisible(true);
            }
        });
    }

    public static int generarNumeroVenta(ArrayList<Venta> datosVentas) {
        ArrayList<Venta> lista = asegurarLista(datosVentas);
        int max = 0;
        for (Venta venta : lista) {
            if (venta != null && venta.getNumero() > max) {
                max = venta.getNumero();
            }
        }
        return max + 1;
    }

    public static ArrayList<Venta> crearNuevaVenta(ArrayList<Venta> datosVentas) {
        ArrayList<Venta> lista = asegurarLista(datosVentas);
        int numero = generarNumeroVenta(lista);
        Venta nueva = new Venta(numero, LocalDateTime.now(), LocalDateTime.now(), null, new ArrayList<>(), 'A');
        lista.add(nueva);
        return lista;
    }

    public static String consultarTodasVentas(ArrayList<Venta> datosVentas) {
        ArrayList<Venta> lista = asegurarLista(datosVentas);
        if (lista.isEmpty()) {
            return "No hay ventas registradas.";
        }
        StringBuilder respuesta = new StringBuilder();
        for (Venta venta : lista) {
            if (venta != null) {
                respuesta.append(venta.toString()).append(System.lineSeparator());
            }
        }
        return respuesta.toString().trim();
    }

    public static String consultarVentaDadoNumero(ArrayList<Venta> datosVentas, int numeroVenta) {
        ArrayList<Venta> lista = asegurarLista(datosVentas);
        for (Venta venta : lista) {
            if (venta != null && venta.getNumero() == numeroVenta) {
                return venta.toString();
            }
        }
        return "No se encontro venta con numero " + numeroVenta + ".";
    }

    public static String consultarVentaDadaPosicion(ArrayList<Venta> datosVentas, char posicionVenta) {
        ArrayList<Venta> lista = asegurarLista(datosVentas);
        if (lista.isEmpty()) {
            return "No hay ventas registradas.";
        }
        char posicion = Character.toUpperCase(posicionVenta);
        if (posicion == 'P') {
            return lista.get(0).toString();
        }
        if (posicion == 'U') {
            return lista.get(lista.size() - 1).toString();
        }
        return "Posicion invalida.";
    }

    public static String consultarVentasDadoEstado(ArrayList<Venta> datosVentas, char estadoVenta) {
        ArrayList<Venta> lista = asegurarLista(datosVentas);
        if (lista.isEmpty()) {
            return "No hay ventas registradas.";
        }
        StringBuilder respuesta = new StringBuilder();
        char estado = Character.toUpperCase(estadoVenta);
        for (Venta venta : lista) {
            if (venta != null && Character.toUpperCase(venta.getEstado()) == estado) {
                respuesta.append(venta.toString()).append(System.lineSeparator());
            }
        }
        if (respuesta.length() == 0) {
            return "No hay ventas para el estado indicado.";
        }
        return respuesta.toString().trim();
    }

    public static String consultarVentasDadaCategoriaPaquete(ArrayList<Venta> datosVentas, String categoriaPaquete) {
        ArrayList<Venta> lista = asegurarLista(datosVentas);
        if (lista.isEmpty()) {
            return "No hay ventas registradas.";
        }
        String categoria = categoriaPaquete == null ? "" : categoriaPaquete.trim().toLowerCase();
        StringBuilder respuesta = new StringBuilder();
        for (Venta venta : lista) {
            if (venta != null && contieneCategoria(venta, categoria)) {
                respuesta.append(venta.toString()).append(System.lineSeparator());
            }
        }
        if (respuesta.length() == 0) {
            return "No hay ventas para la categoria indicada.";
        }
        return respuesta.toString().trim();
    }

    public static void generarArchivoObjetosVentas(ArrayList<Venta> datosVentas) {
        ArrayList<Venta> lista = asegurarLista(datosVentas);
        Path ruta = Paths.get("ventas.dat");
        try (ObjectOutputStream salida = new ObjectOutputStream(Files.newOutputStream(ruta))) {
            salida.writeObject(lista);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No fue posible guardar ventas: " + ex.getMessage());
        }
    }

    public static void recuperarVentasDesdeArchivoObjetos() {
        Path ruta = Paths.get("ventas.dat");
        if (!Files.exists(ruta)) {
            JOptionPane.showMessageDialog(null, "No existe archivo de ventas.");
            return;
        }
        try (ObjectInputStream entrada = new ObjectInputStream(Files.newInputStream(ruta))) {
            Object datos = entrada.readObject();
            if (datos instanceof ArrayList) {
                @SuppressWarnings("unchecked")
                ArrayList<Venta> ventas = (ArrayList<Venta>) datos;
                datosVentas = ventas;
            }
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "No fue posible recuperar ventas: " + ex.getMessage());
        }
    }

    public static void actualizarVenta(ArrayList<Venta> datosVentas, int numeroVenta, char operacion) {
        ArrayList<Venta> lista = asegurarLista(datosVentas);
        char operacionNormalizada = Character.toUpperCase(operacion);
        for (Venta venta : lista) {
            if (venta != null && venta.getNumero() == numeroVenta) {
                if (operacionNormalizada == 'C' || operacionNormalizada == 'P') {
                    venta.setEstado(operacionNormalizada);
                    venta.setFechaHoraActualizacion(LocalDateTime.now());
                }
                return;
            }
        }
    }

    public static void generarArchivoObjetosClientes(ArrayList<Cliente> datosClientes) {
        ArrayList<Cliente> lista = asegurarListaClientes(datosClientes);
        Path ruta = Paths.get("clientes.dat");
        try (ObjectOutputStream salida = new ObjectOutputStream(Files.newOutputStream(ruta))) {
            salida.writeObject(lista);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No fue posible guardar clientes: " + ex.getMessage());
        }
    }

    public static void recuperarClientesDesdeArchivoObjetos() {
        Path ruta = Paths.get("clientes.dat");
        if (!Files.exists(ruta)) {
            JOptionPane.showMessageDialog(null, "No existe archivo de clientes.");
            return;
        }
        try (ObjectInputStream entrada = new ObjectInputStream(Files.newInputStream(ruta))) {
            Object datos = entrada.readObject();
            if (datos instanceof ArrayList) {
                @SuppressWarnings("unchecked")
                ArrayList<Cliente> clientes = (ArrayList<Cliente>) datos;
                datosClientes = clientes;
            }
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "No fue posible recuperar clientes: " + ex.getMessage());
        }
    }

    private static ArrayList<Venta> asegurarLista(ArrayList<Venta> datos) {
        if (datos == null) {
            return new ArrayList<>();
        }
        return datos;
    }

    private static ArrayList<Cliente> asegurarListaClientes(ArrayList<Cliente> datos) {
        if (datos == null) {
            return new ArrayList<>();
        }
        return datos;
    }

    private static boolean contieneCategoria(Venta venta, String categoria) {
        if (venta == null || venta.getSusPaquetesTuristicos() == null) {
            return false;
        }
        for (PaqueteTuristico paquete : venta.getSusPaquetesTuristicos()) {
            if (paquete == null) {
                continue;
            }
            if ("unico".equals(categoria) && paquete.getClass().getSimpleName().equals("PaqueteTuristicoUnico")) {
                return true;
            }
            if ("multiple".equals(categoria) && paquete.getClass().getSimpleName().equals("PaqueteTuristicoMultiple")) {
                return true;
            }
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
